# Generated by Django 3.2.9 on 2021-11-03 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('title', models.TextField(max_length=200)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('equity_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
