# Generated by Django 3.2.9 on 2021-11-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('title', 'game')},
        ),
    ]
