# Generated by Django 3.2.9 on 2021-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='ticker',
            field=models.TextField(max_length=5),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='game_rank',
            field=models.IntegerField(default=1),
        ),
    ]
