# Generated by Django 3.2.9 on 2021-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='shares',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shares',
            field=models.IntegerField(null=True),
        ),
    ]
