# Generated by Django 3.2.9 on 2021-11-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0002_auto_20211110_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='shares',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shares',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
    ]
