# Generated by Django 3.2.9 on 2021-11-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0002_auto_20211112_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='game_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
