# Generated by Django 3.2.9 on 2021-11-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("trade_simulation", "0003_portfolio_game_rank")]

    operations = [
        migrations.RemoveField(model_name="game", name="end_date"),
        migrations.RemoveField(model_name="game", name="start_date"),
    ]
