# Generated by Django 3.2.9 on 2021-11-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0004_holding_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='value',
        ),
    ]
