# Generated by Django 3.2.9 on 2021-11-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0005_remove_holding_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='equity_value',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='total_value',
        ),
    ]
