version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.7.3
      - image: circleci/postgres:10.5
    environment:
      DATABASE_URL: postgres://postgres:@localhost/circle_test
      DJANGO_SECRET_KEY: test
      DJANGO_READ_DOT_ENV_FILE: True
      DJANGO_SETTINGS_MODULE: zappa.settings
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v001-app-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/local.txt
      - save_cache:
          key: v001-app-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          name: Add python project to path
          command: 'echo "$(realpath .)/app" > venv/lib/python3.7/site-packages/app.pth'
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test
