version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.9.7
      - image: circleci/postgres:10.5
    environment:
      DATABASE_URL: postgres://postgres:@localhost/circle_test
      DJANGO_SECRET_KEY: test
      DJANGO_READ_DOT_ENV_FILE: True
      DJANGO_SETTINGS_MODULE: zappa.settings
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v001-app-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v001-app-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          name: Add python project to path
          command: 'echo "$(realpath .)/app" > venv/lib/python3.9/site-packages/app.pth'
      - run:
          name: Migrate DB
          command: |
           . venv/bin/activate
           python manage.py migrate
           python manage.py makemigrations
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run --source='.' manage.py test
            coverage html
      - run:
          name: Run Flake8
          command: |
            . venv/bin/activate
            python3 -m flake8 --extend-exclude=./.venv,./zappa/.venv > bugs.txt


workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job