# Generated by Django 3.2.9 on 2021-12-11 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('title', models.TextField(max_length=200, unique=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=14)),
                ('rules', models.TextField(blank=True, max_length=200, null=True)),
                ('winner', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('game_rank', models.IntegerField(default=1)),
                ('title', models.TextField(max_length=200)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=10000.0, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_simulation.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('title', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('ticker', models.TextField(max_length=200)),
                ('trade_type', models.TextField(max_length=200)),
                ('shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('bought_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_simulation.portfolio')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('contract', models.TextField(max_length=25)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_simulation.portfolio')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('ticker', models.TextField(max_length=5)),
                ('shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_simulation.portfolio')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
