# Generated by Django 3.2.9 on 2021-11-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0002_auto_20211119_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_on']},
        ),
    ]
