# Generated by Django 3.2.9 on 2021-12-02 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0003_auto_20211119_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AlterModelOptions(
            name='holding',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_simulation.portfolio'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('contract', models.TextField(max_length=25)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_simulation.portfolio')),
            ],
        ),
    ]
