# Generated by Django 3.2.9 on 2021-12-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0005_alter_transaction_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_on']},
        ),
    ]
