# Generated by Django 3.2.9 on 2021-12-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_simulation', '0006_auto_20211202_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
